server.port: 8090

info.version: ${project.version}

configuration:
   owner:
      name: Nikos
      lastName: Alexiou

startUpOptions:
   enableDatabaseOnStartUp: true
   cleanUpDatabasesOnStartUp: true
   enableLogging: true
   httpTimeOut: 30000
   
threadpool:
   corepoolsize: 2000
   maxpoolsize: 4000

time-zone: Europe/Athens

randomValues:
    password: ${random.value}
    intValue: ${random.int}
    intValueRange: ${random.int[1,99]}
    intUpperLimit: ${random.int(10)}
    longValue: ${random.long}
    longValueRange: ${random.long[111111111111,999999999999]}
    uuid: ${random.uuid}

    
test:
   foo: typeSafeVariable    

#sets active profile   
#spring.profiles.active: dev   