server.port: 8090

info.version: ${project.version}

configuration:
   owner:
      name: Nikos
      lastName: Alexiou

startUpOptions:
   enableDatabaseOnStartUp: true
   cleanUpDatabasesOnStartUp: true
   enableLogging: true
   httpTimeOut: 30000
   
threadpool:
   corepoolsize: 2000
   maxpoolsize: 4000

time-zone: Europe/Athens